spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 2301
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    properties:
      properties:
        hibernate.format_sql: true
  sql:
    init:
      encoding: UTF-8