server:
  port: 8081

spring:
  profiles:
    active: dev1
  application:
    name: web-library
  jackson:
    default-property-inclusion: non_null

application:
  security:
    jwt:
      secret-key: 1111
      expiration: 1000
      refresh-token:
        expiration: 2000


logging:
  level:
    org.springframework: error
    org.hibernate: error