spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: accounting
    password: accounting
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  sql:
    init:
      encoding: UTF-8
      mode: always
      data-locations: classpath:/data/role.sql